### ISSUE TITLE
Validation failed

### ISSUE THREAD

**Issue by sturtzel** [documaster/noark-extraction-validator#33] opened 2017-04-10 12:49 UTC
2017-04-10 08:54:49,433 ERROR c.d.v.v.n.Noark53Validator [main] Noark 5.3 validation failed.
com.documaster.validator.exceptions.ValidationException: Validation has been stopped due to unrecoverable extraction integrity violation.
        at com.documaster.validator.validation.noark53.Noark53Validator.validateStructure(Noark53Validator.java:187) ~[noark-extraction-validator-0.2.0-SNAPSHOT.jar:0.2.0-SNAPSHOT]
        at com.documaster.validator.validation.noark53.Noark53Validator.run(Noark53Validator.java:88) [noark-extraction-validator-0.2.0-SNAPSHOT.jar:0.2.0-SNAPSHOT]
        at com.documaster.validator.main.Run.main(Run.java:49) [noark-extraction-validator-0.2.0-SNAPSHOT.jar:0.2.0-SNAPSHOT]

Med -ignore-non-compliant-xml gikk den gjennom.

**Comment by ivaylomitrev** [comment] 2017-04-10 12:57
Hi,

If you are running the validator tool with the `-ignore-non-compliant-xml` flag and you are still getting the error message then the most likely reason for it is the issue described in Issue #28. However, as far as I can see from the attached stack trace this is a controlled termination that should only be reproducible if the `ignore-non-compliant-xml` **was not specified**. As a result, the issues might not be related.

In order to be able to address it I will need additional information.

May I ask you for the following:
- the whole command you used to run the validation
- the whole execution log (you have only provided a part of it here)
- the generated XML/EXCEL_XLSX reports (if any were generated and if they **do not contain sensitive information**)

**Comment by ivaylomitrev** [comment] 2017-04-10 12:58
A follow-up:
If you are unable to attach the reports due to the fact that they contain sensitive information, could you attach the error messages printed in the `Exceptions` section of the Excel report?

**Comment by sturtzel** [comment] 2017-04-10 13:15
Translated original: With the ignore flag it completed. Without it did not. The data is my test data, so I'll upload.

There wasn't any log in this case.

**Comment by ivaylomitrev** [comment] 2017-04-10 13:18
Generally, this is the expected behavior *if the XML files in the extraction do not match the schemas distributed with the Noark 5 standard*.

Taken from the README:
> Making the validation process less strict is also possible. The default behavior of the validator is to stop execution if an XML file does not comply with the corresponding Noark XSD schema.

This is probably the case. Furthermore, this should also be logged in the `Exceptions` sheet of the Excel report or in the `Exceptions` section of the XML report.

**Comment by sturtzel** [comment] 2017-04-10 13:23
The exception section of the excel sheet contained the error message only, no more info.

Yes, I've edited the XSDs to include "may include additional codes". I've also changed som minOccurs as some data is pre Noark 5 and thus miss new Noark 5 fields.

Looks like the missing option should result in a fatal error? With the ignore option it completed.

**Comment by ivaylomitrev** [comment] 2017-04-10 13:45
> The exception section of the excel sheet contained the error message only, no more info.

It is one of the `.xml` tests then that has failed (arkivstruktur.xml, or endringslogg.xml, for example). It should be marked `red` (errors exist) and it should list one or more errors explaining why the XML file does not match the XSD schema in one way or another. As you have stated in your previous comment - the reason should be missing codes in the XSD.

> Yes, I've edited the XSDs to include "may include additional codes". I've also changed som minOccurs as some data is pre Noark 5 and thus miss new Noark 5 fields.

A modified XSD will not force the validator to stop execution. **Only invalid XML files will**. That is, a required XML file that:
1. could not be found OR
2. is not a well-formed XML file OR
3. does not match its corresponding Noark schema. Note that I mean the schema distributed with the standard, not the one included in the extraction package. I urge you to take a look at the description of test `P9` and the like (`P6`, `P4`, `P2`):
> Validity of arkivstruktur.xml (existence, well-formedness, compliance with schemas)
> Produces warnings when arkivstruktur.xml does not comply with the package arkivstruktur.xsd. Produces errors when arkivstruktur.xml does not comply with the Noark arkivstruktur.xsd.

Errors (non-compliance with the Noark schemas) are considered fatal and force stop the execution under normal circumstances (i.e. without the `-ignore-non-compliant-xml` flag). The only way to force the validator to complete a full validation cycle for invalid extractions is to run it with the `-ignore-non-compliant-xml` (as you have done).

`-ignore-non-compliant-xml` was introduced as a result of a requirement by Torbjørn to be able to validate extractions whose XML files do not match the Noark XSD schemas. As stated in the README.md file of the project, this flag should be used with great care and only if an extraction is known and permitted to be invalid with regard to Noark 5. A regular validation should generally not specify this flag as this would generally mean that the extraction is inherently invalid.

Let me know if something is unclear or I have misunderstood you in some way. If not, I will close the issue as, it seems to me, it is simply a result of the expected behavior of the `-ignore-non-compliant-xml` flag.

**Comment by ivaylomitrev** [comment] 2017-04-13 06:45
Hi @sturtzel,

I am closing this issue with a status of `wontfix` as our discussion has led me to believe that this is the expected behavior of the tool. Let me know if there was any misunderstanding on my side and there is an issue that should be looked into. Feel free to re-open the ticket if this is the case.

**Closed** 2017-04-13 06:46 UTC
Labels: wontfix
